# -*- coding: utf-8 -*-
"""fake-and-real-news-detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10G8o9GivUsQJMUHBdLXrkPJI6nYYu_LB
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import os
os.environ['KAGGLE_API_TOKEN'] = userdata.get('KAGGLE_API_TOKEN')

!pip install -q kaggle
!kaggle datasets download -d clmentbisaillon/fake-and-real-news-dataset
!unzip -q fake-and-real-news-dataset.zip -d fake_news_data

fack_data=pd.read_csv(r'/content/fake_news_data/Fake.csv')
true_data=pd.read_csv(r'/content/fake_news_data/True.csv')

fack_data['label']=0
true_data['label']=1

df=pd.concat([fack_data,true_data],ignore_index=True)

df

df=df.sample(frac=1).reset_index(drop=True)

df['content']=df['title']+' '+df['text']
x=df['content']
y=df['label']



from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,stratify=y,random_state=2)

from tensorflow.keras.layers import *
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import pad_sequences

token=Tokenizer()
token.fit_on_texts(x_train)

vocab_size = len(token.word_index) + 1

# x=token.texts_to_sequences(x)

# x=pad_sequences(x,maxlen=50,padding='post')
x_train_seq=pad_sequences(token.texts_to_sequences(x_train),maxlen=250,padding='post')
x_test_seq=pad_sequences(token.texts_to_sequences(x_test),maxlen=250,padding='post')

model=Sequential()
model.add(Input(shape=(250,)))
model.add(Embedding(input_dim=vocab_size,output_dim=2))
model.add(SimpleRNN(32))
model.add(Dense(1,activation='sigmoid'))

model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

model.summary()

model.fit(x_train_seq,y_train,epochs=10,batch_size=32,validation_data=(x_test_seq,y_test))

loss,accuracy=model.evaluate(x_test_seq,y_test)
print("Test Accuracy:", accuracy)

pred=model.predict(x_test_seq)
pred=(pred>=0.5).astype(int)

from sklearn.metrics import confusion_matrix,classification_report

print(confusion_matrix(pred,y_test))
print(classification_report(pred,y_test))

